channels:
- conda-forge
dependencies:
- python=3.12.3
- pip<=24.2
- pip:
  - mlflow==2.18.0
  - cffi==1.17.1
  - cloudpickle==3.0.0
  - cytoolz==0.12.2
  - dask-expr==1.1.13
  - defusedxml==0.7.1
  - distributed==2024.8.2
  - lightgbm==4.5.0
  - lz4==4.3.2
  - matplotlib==3.9.2
  - scikit-learn==1.5.1
  - zstandard==0.23.0
name: mlflow-env
